#!/usr/bin/env bash
# Generates all maps from the template map and packs them as PBOs

# switch to project root
cd ..
missionWhitelist="// Warning: This file was generated by a script. Do not edit it manually!\n"
for file in $(ls -v pbo/*.pbo); do
	file=$(basename -- ${file%.*})
	missionWhitelist="$missionWhitelist\"$file\",\n"
done
missionWhitelist="${missionWhitelist%,*}\n"
printf "$missionWhitelist" > missionWhitelist.dat
